# @format

services:
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
 